# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  socket: /tmp/mysql.sock


development:
  <<: *default
  database: db_development
  username: seiya_development
  password: Sk100106_development

test:
  <<: *default
  database: db_test
  username: seiya_test
  password: Sk100106_test

production:
  <<: *default
  database: db_production
  username: seiya_production
  password: Sk100106_production

